# 开发环境配置
app:
  env: "dev"

server:
  mode: "debug"

log:
  level: "debug"
  format: "json"

# 限流配置
rate_limit:
  enabled: false
  requests_per_second: 100
  burst: 200

database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "admin_db"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  type: "node"
  pool_size: 10
  min_idle_conns: 2
  max_retries: 2
  dial_timeout: 3
  read_timeout: 3
  write_timeout: 3
