# 默认配置文件
app:
  name: "Admin"
  port: 8080
  env: "dev"

server:
  mode: "debug"  # debug, release, test

# 日志配置
log:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json, console

# 限流配置
rate_limit:
  enabled: false
  requests_per_second: 100
  burst: 200


# 数据库配置
database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "admin_db"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # seconds


redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  type: "node"            # node 或 cluster
  pool_size: 10
  min_idle_conns: 2
  max_retries: 2
  dial_timeout: 3         # seconds
  read_timeout: 3         # seconds
  write_timeout: 3        # seconds

# JWT配置
jwt:
  access_secret: "ngV/yUNRUCUpAzN2MUBgaYQhKNiYH1wudhWVdN/3yT4=" # access token密钥 (建议生产环境使用环境变量)
  access_expire: 3600         # 1小时 (3600秒)
  refresh_secret: "vO58bdcDhf8s7LqvFGStwJ70GfBnSgrc6fTsfESYhAo=" # refresh token密钥 (建议生产环境使用环境变量)
  refresh_expire: 86400     #  7 天 refresh token过期时间，防止丢失后还可以用7天
  issuer: "admin"            # token签发者
