# 生产环境配置
app:
  env: "prod"
  port: 9090

server:
  mode: "release"

log:
  level: "info"
  format: "json"

database:
  host: "postgres"
  port: 5432
  user: "root"
  password: "root"
  dbname: "content_center"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600


